danparizher/Pax-Academia

main.py

Hotfix for heartbeat block

---

cogs/Alerts.py

Fix discord.Forbidden error

---

.gitignore
cogs/DeepL.py
main.py

Fixes issue #43 along with some minor refactoring.
I did verify that the command still works:
https://user-images.githubusercontent.com/44247924/201419287-6e103515-fb7f-463c-9637-2ce7b27a1165.mp4

fix: Make `/translate` asynchronous.

---

.gitignore
cogs/Alerts.py
cogs/MessageCounter.py
main.py

Database Updating

---

cogs/Surveys.py

Fix forbidden error

---

cogs/Alerts.py
cogs/DeepL.py
cogs/Information.py
cogs/MerriamWebster.py
cogs/MessageCounter.py
cogs/Misc.py
cogs/PubChem.py
cogs/Wikipedia.py

Add documentation for all functions across the project

Project wide documentation

---

README.md
cogs/StaffRequirements.py

- Fixed staff requirements not working if under 30 days but over a year.
- Moved the form link to the env

fixed staff requirements

---

cogs/Moderation.py

These messages are annoying, not useful.

feat: Do not consider same-channel messages 'multiposts'

---

cogs/DeepL.py
cogs/PubChem.py
cogs/Wikipedia.py
util/threaded_async.py

The same issue as #43 is affecting both `Wikipedia` and `PubChem`. This PR extracts the solution into a `util`, then applies the solution to those two cogs.

fix: make network requests asynchronous

---

cogs/Moderation.py

I keep seeing messages like this, where the person deletes their multipost after being warned:
This gif is pretty self-explanatory:

feat: Delete "Multi-Post Warning" if the author deletes their message

---

cogs/Moderation.py

Resolves issue #83
Deletes multi-posted messages after 2 posts:
https://github.com/Arborym/Pax-Academia/blob/a309fe879866a1fb56bd1e623da613468dd1670c/cogs/Moderation.py#L222-L224
https://user-images.githubusercontent.com/44247924/204182373-b0a2c748-8fd2-406d-9d65-cabce3c0b26e.mp4

feat: Delete multiposts

---

README.md
cogs/Moderation.py

Resolves issue #86
@sebastiaan-daniels Please add `ALLOW_MULTIPOST_FOR_ROLE=Staff` to `.env` 
https://user-images.githubusercontent.com/44247924/204941013-fb101889-08e3-4f38-acab-a7f2f9664f82.mp4

feat: Allow Staff to multipost

---

cogs/MerriamWebster.py

- Fixed HTML scraping for phonetic pronunciations
- Embed fields will be added only if there are values returned
- Remove Synonyms and Antonyms temporarily, the list logic on MW changed entirely, will need a second look on retrieving them

Rework Definitions

---

cogs/Moderation.py

Resolves #94 
https://user-images.githubusercontent.com/44247924/206022276-3daede57-ef4e-48ef-bac4-3984d1e706a9.mp4

fix: Don't send duplicate multipost warnings

---

cogs/Moderation.py

chore: Do not store users' filenames in bandwidth database

---

cogs/DetectAI.py
main.py
requirements.txt
setup.bat

Add a `/detect-ai` slash command that allows users to enter text and see a screenshot of the AI detection analysis coming from http://gltr.io/dist/index.html.

Add AI Detection functionality

---

cogs/Alerts.py

Remove tutor_alerts, fix character limit

---

cogs/DeepL.py
cogs/DetectAI.py
cogs/MerriamWebster.py
cogs/PubChem.py
cogs/Wikipedia.py

Make error messages ephemeral

---

cogs/Alerts.py

Czar.cyborg alert fix

---

cogs/StaffRequirements.py

As discussed with Schuler, I've added a quick check for the minimal message amount whilst we wait for the proper StaffAppsV2
implementation.
This code was made on the fly and is untested, so someone might want to have a look at this before merging

Add minimal message requirement to staff app

---

cogs/StaffRequirements.py

https://discord.com/channels/238956364729155585/1040360228388098159/1073443619089952879

fix: `joined_at` is `None` when `ctx.author` is a `discord.User`  

---

README.md
cogs/Misc.py

Adds the `/dump_database` command which dumps all tables into CSV files
https://user-images.githubusercontent.com/44247924/219848868-2b65c884-c872-4e5b-a1af-b167c46eec82.mp4

feat: Add ability to dump the database

---

cogs/MessageCounter.py
main.py
util/ERD.mdj
util/db_builder.py
util/db_update.py

- This PR updates the database to include counting messages in help channels marked by "Help" in the category name.
- Maintainers:
Please run `util/db_update.py` to alter the user table.
- Resolves #164

Update: Count messages in help channels

---

cogs/DetectAI.py
cogs/Dictionary.py
cogs/MessageCounter.py
cogs/README.md
main.py
util/db_update.py

Getting rid of leading whitespace, following MD format rules

Get rid of whitespaces in `README.md`

---

cogs/StaffAppsBackoffice.py
util/db_builder.py

V2.1 of staffapplications fixes and addresses most comments in #162
- closes #162

StaffApps v2.1

---

.gitignore
cogs/Alerts.py
cogs/DeepL.py
cogs/DetectAI.py
cogs/Dictionary.py
cogs/Misc.py
cogs/Moderation.py
cogs/PubChem.py
cogs/Rules.py
cogs/StaffAppsBackoffice.py
cogs/StaffAppsUser.py
cogs/Surveys.py
cogs/Tips.py
cogs/Wikipedia.py
util/Logging.py
util/db_builder.py
util/db_update.py

With discord's recent changes to how discord usernames work, we need to adapt to this as well.
Most of the changes were in the logging module, and some changes were made in the staff apps.
Also added some logging to cogs where there was none
fixes #184 
closes #178

Bugfix / enhancement: Adapt to discords new usernames

---

util/Logging.py
util/db_builder.py
util/db_update.py

Use Pathlib instead of native methods

Use Pathlib instead of native methods

---

cogs/DeepL.py

I have never made a PR before, so sorry if this is formatted poorly. Let me know if I did this correctly! Fixes #190

Added an error message when user tries to translate language A ⇔ A

---

cogs/Alerts.py
cogs/Dictionary.py
util/EmbedBuilder.py

Limit embed fields to maximum number of allowed characters

---

main.py
util/deepl_update.py

make deepl update on bot restart

make deepl update on bot restart

---

util/Logging.py

Thanks to @pharmony01 for being patient zero

Add user to db if no messages sent

---

cogs/Alerts.py

Discussion here: https://discord.com/channels/238956364729155585/554420229283905558/1136480947311738960

fix: Enable alerts from authors who have no alerts

---

ENVIRONMENT.md
cogs/DetectCode.py
cogs/Tips.py
main.py

Fixes #197 by adding adding code detection using characters common to code blocks. This seems really simple, but I tested it on a bunch of messages from the several CS related channels under the Computer Science category and it performed really well.

Added CodeDetect Cog

---

cogs/README.md
util/README.md
util/db_builder.py

I changed the way the docs are written. 
The documentation for each cog is formatted like so:
- Commands implemented:
- `command`
- Description:
- Description
If I have missed any functionalities in certain cogs or utils, please let me know and I will update them accordingly.

created new documentation for cogs and utils

---

.gitignore
util/dev.py

Because the dev feedback thing was way to overcomplicated and could've been much simpler

Ska.better devtools

---

ENVIRONMENT.md
cogs/README.md
cogs/surveys.py
cogs/wikipedia.py
main.py
util/embed_builder.py

Fixes surveys.py to not log every message and moves a hardcoded channel ID to .env

---

code_detection/tests/__init__.py
cogs/alerts.py
cogs/message_counter.py
cogs/pubchem.py
cogs/rules.py
cogs/staffapps_backend.py
cogs/staffapps_frontend.py
cogs/surveys.py
cogs/tips.py
cogs/wikipedia.py
message_formatting/embeds.py
message_formatting/views/feedback.py
util/limiter.py
util/logger.py

Fixes all remaining type errors across the entire repository, according to Pylance.
There are a few minor adjustments to logic trees (since naturally many of these type errors actually reveal real runtime errors); feel free to ask questions about the less obvious ones :)
Closes #223

refactor(part 2): resolve typing errors throughout entire codebase

---

ENVIRONMENT.md
cogs/misc.py

Change env names, apparently ALLOW_DETECT_AI_GUILD wasn't being used

Change env names

---

code_detection/python.py

Bugfix: fix `RecursionError` in code detection

Bugfix: fix `RecursionError` in code detection

---

code_detection/__init__.py
code_detection/python_traceback.py
code_detection/tests/__init__.py
code_detection/tests/helpers.py
code_detection/tests/python_traceback.py

fixes: #265
https://discord.com/channels/238956364729155585/791697255835893821/1145122794582065192
(thanks @danparizher for reviving this PR after a month of it sitting as a draft)

feat: Add `code_detection` for Python tracebacks

---

cogs/misc.py
requirements.txt

This PR adds the short commit ID of the currently running version of Pax to the ping command. This way anyone (Mostly @danparizher ) can see what version production is on and can easily call me out when it is not up to date

Enhancement: Add commit ID to /ping

---

.github/workflows/dependencies.yml

fixes https://github.com/danparizher/Pax-Academia/pull/308#pullrequestreview-2745212807

fix: use python3.11 in dependencies.yml job
