danparizher/Pax-Academia

cogs/Moderation.py

I noticed this interaction:
The person simply said "Correct" twice. This is allowed, and the bot should not have warned the user for multiposting.
For message content, require there to be at least 15 characters before flagging it as a multipost. Furthermore, I've removed all punctuation and digits from the detection mostly to help prevent emojis from being flagged.

fix: Make multi-post detection stricter for message content

---

cogs/StaffRequirements.py

Hey, I merged the two embeds into one as suggested in the dev channel, along with a few other cosmetic changes. Here are some screenshots. Any thoughts?
List of changes I've made:
- Combined the two separate embeds into one
- Change the color of the embed to green or red depending on whether the user meets the requirements for staff or not
- If the user meets the requirements, show the staff app link as a button rather than a URL within the embed description. I feel like it's more intuitive for the end user and looks more polished.
- **⚠️ AND AND AND** I changed the logic for how the requirements are checked. Instead of manually computing the join and creation date and year and comparing them as integers, I compare them as `timedelta`'s. Check the comments right above the if-statement. …

cosmetic changes to /check-requirements

---

cogs/Alerts.py

This PR converts all user input into a base64 string before inserting/fetching/committing to and from the database.
This protects the database against various forms of SQL injection.
It is not necessary for bandwith or messagecount as users have no way of accessing these queries

Protect user input against SQLi

---

cogs/Wikipedia.py

SQLite does not support multithreaded access to a single database object, which is made clear in this error:
```
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 1868 and this is thread id 8852.
```
This PR moves the bandwidth logging back to the host thread.

fix: Wikipedia multithreaded access to SQLite database

---

cogs/Moderation.py

If someone multiposts something, then immediately deletes their message, we get an error when trying to reply to it with the warning:
```
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In message_reference: Unknown message
```
This PR just gracefully handles such an error by `pass`ing when it is raised.

fix: Gracefully handle multiposts that are quickly deleted

---

README.md
cogs/Moderation.py

#84 added the emoji with the ID 1046975245761912873, which is incorrect.
The correct ID is 1046975187930849280, which you can test by copy pasting `<:multipost:1046975187930849280>` into discord. You'll notice that it will be formatted as the correct emoji.

fix: Wrong multipost emoji ID

---

.gitignore
cogs/Alerts.py

- For ease of accessibility, users will now receive a CSV file instead of a .SQLITE file when calling the Alerts table.
- Addresses #90

Replace view-db db with csv

---

cogs/Alerts.py

All users were able to access the /view-db command and get full access to the entire database(s)
This was solved by restricting the command to staff role only in the server settings themselves.
This does not work because anyone can invite the bot to their own server and use the command with no restrictions.
Even though the invite link is not public anyone can get the link by doing:
```
https://discord.com/oauth2/authorize?client_id=BOTID&permissions=8&scope=applications.commands%20bot
and just replacing the BOTID with Pax Academia's ID (1033864301045362699)
```
This hotfix temporarily fixes the command by only allowing 4 people access to the command. A better fix needs to be implemented in the future, but the bot needs to be back online as soon as possible.

!IMPORTANT! Hotfixed security issue

---

cogs/Alerts.py

This PR removes (part) of the hard-coding in /view-db.
Before, every table was hard coded, turned into a csv file and uploaded. These changes make this command future-proof (up to 10 tables) so that no changes need to be made when (eventually) more tables will be added to the database.

Improved database submission upon /view-db

---

cogs/Moderation.py

`delete_previous_multipost_warnings` looks at `self.multipost_warnings` and deletes any messages that match the same fingerprint. This will include the warning that was just sent. This PR simply moves the deletion above the new warning's addition to `self.multipost_warnings`, so that it will not get deleted.

fix: Don't delete the warning immediately after sending it

---

cogs/Alerts.py
util/db_update.py

This PR:
1. Makes the `add-alert` command escape invalid regex before inserting it into the database.
2. Updates the type hinting to fix several errors
3. refactors a couple of related logical issues & code quality things
4. adds a migration to `db_update.py` which will update all of our existing alerts

fix: Escape bad regex and resolve type errors

---

cogs/StaffAppsUser.py

During a routine checkup of the logfiles and db integrity, The count of successful applications was higher than the count(*) of applications in the database. After investigating I found it was due to incorrect placing of the log message in the source code.
(The application would already be logged as submitted when the user pressed the button to go to the next questions)

Bugfix: Incorrect logging

---

cogs/Alerts.py
cogs/DeepL.py
cogs/DetectAI.py
cogs/Dictionary.py
cogs/Misc.py
cogs/PubChem.py
cogs/Rules.py
cogs/StaffAppsBackoffice.py
cogs/StaffAppsUser.py
cogs/Surveys.py
cogs/Tips.py
cogs/Wikipedia.py
util/ERD.mdj
util/Logging.py
util/db_builder.py
util/db_update.py

Because some people [don't know how to behave](https://discord.com/channels/238956364729155585/238956364729155585/1092872600331501609), The ability to limit specific users from using (parts) of the bot has been implemented.
This feature does **not** serve as a substitute to normal moderation, and will _only_ be used in case of bot abuse. Reasons for this could be:
- Setting up alerts to spam the bot
- trying to abuse rate limits of other sites
- trying to manipulate the db in malicious ways
A user can be limited in 3 different ways:
- User is limited from interacting with the database
- User is limited from db & all commands that require internet
- User is fully limited from any & all commands
closes #186

Safety/Enhancement: Add ability to limit users

---

cogs/MessageCounter.py

The user table was updated in the db, This needs to be reflected when a user is added.

Hotfix: Add limitLevel in addUser()

---

cogs/StaffAppsBackoffice.py

embed.add_field(name=name[:256], value=value[:1024], inline=inline)
~~~~~^^^^^^^
TypeError: 'datetime.datetime' object is not subscriptable

Fix "Datetime object not subscriptable"

---

cogs/alerts.py
cogs/pubchem.py
cogs/wikipedia.py

`from __future__ import annotations` converts _all_ type annotations into strings. Pycord reads these type hints at runtime to determine the schema of slash commands, which makes it incompatible with `__future__.annotations`.
Rather than removing this import, we can just explicitly tell pycord the type for each option (via `@option(name, type)`) so that it doesn't need to be inferred.

fix: pycord cannot process string type hints

---

ENVIRONMENT.md
cogs/alerts.py
cogs/misc.py
util/limiter.py

a) This PR adds a decorator to the `limiter.py` file which can be imported in a cog.
Decorating a slash command with this wrapper will make the command usable only in the guild set in the `env`.
b) All alert commands have been decorated with this wrapper
(closes #244 )
@sebastiaan-daniels : Update production ENV on merge

feat: Add ability to make a command server-only

---

cogs/staffapps_backend.py

This hotfix turns a datetime object in `staffapps_backend` into a string before sending it to `embedbuilder` so the string can be sliced.

hotfix: Datetime object not subscribtable

---

CONTRIBUTING.md
README.md

Pax Academia started out as a small bot on the HwH discord server to fill in some gaps where small features were missing.
Today, it is a complex project with an entire team working on it, serving more than 150 thousand users daily*.
At the moment, we have a group of code owners which each need to accept every pull request. Which is good for security, but bad for speed. Some dependencies and bugfixes simply need to be implemented faster, as our production deployment needs to be up to date and correct.
This new document aims to outline new guidelines and rules for contributing to this project. Focusing heavily on creating good, complete PRs which can be implemented quickly for smaller fixes, and thoroughly reviewed for bigger feats.
I highly recommend carefully reviewing this proposal, and …

[Proposal] Docs: A new way to contribute code to Pax.

---

cogs/surveys.py

Broken replies are annoying! This PR deletes the "Survey Detected" message once the user deletes their message containing a survey (up to one hour after they send it, after which the cache is purged). (discord discussion: [link](https://discord.com/channels/238956364729155585/1040360228388098159/1163828958740094976))

fix: auto-delete survey messages

---

cogs/tips.py

When a user sends an anonymous tip, the bot sends the same tip twice due to a missing return statement. This PR adds this statement.
- closes #269

bugfix: missing return statement in `tips`

---

code_detection/base.py

The error:
```
Ignoring exception in on_message
Traceback (most recent call last):
File "C:\Production code\Pax-Academia\venv\Lib\site-packages\discord\client.py", line 378, in _run_event
await coro(*args, **kwargs)
File "C:\Production code\Pax-Academia\cogs\detect_code.py", line 105, in on_message
if autoformat and (detection_result := code_detection.detect(message.content)):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Production code\Pax-Academia\code_detection\__init__.py", line 23, in detect
best_match = max(
^^^^
File "C:\Production code\Pax-Academia\code_detection\__init__.py", line 25, in <lambda>
key=lambda d: (d.probable_lines_of_code, d.lines_of_code),
^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Production code\Pax-Academia\code_detection\base.py", line 472, in probable_lines_of_code …
```

fix: Edge case where message has no content throws error

---

.github/workflows/dependencies.yml

This PR adds the base branch parameter to the pull request, which fixes the following build error:
`The 'base' and 'branch' for a pull request must be different branches. Unable to continue.`

Bugfix: Add base branch to pull request

---

cogs/misc.py

This PR fixes (I think?) the issue where the bot does not fetch the origin when displaying whether it is up to date or not.
- closes #277

Bugfix: /ping correctly shows whether the bot is up to date or not

---

.github/workflows/dependencies.yml

Fixes:
```
Run git checkout -b update-requirements
Switched to a new branch 'update-requirements'
[update-requirements 6a47132] Update requirements.txt
1 file changed, 4 insertions(+), 4 deletions(-)
To https://github.com/danparizher/Pax-Academia
! [rejected]        update-requirements -> update-requirements (fetch first)
error: failed to push some refs to 'https://github.com/danparizher/Pax-Academia'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Error: Process completed with exit code 1.
```

bugfix: pull from source

---

ENVIRONMENT.md
cogs/detect_media_spam.py
cogs/misc.py
main.py

Monitors specified channels to watch for large quantities of media. If a threshold is crossed, all recent media can be deleted*.
\* No media is being deleted yet, we're still testing to determine what the appropriate threshold should be. This PR adds a command to display the current "media percent" from various history lengths. We'll enable the deletion once we're happy with a threshold.

feat: Detect & Destroy media spam

---

cogs/message_counter.py

Due to (presumably) some API update the `category.name` changed from `my category name` to `My Category Name`.
=> Added a `.lower()` method to account for this
Fixes #290

HotFix: Fix help message counter

---

cogs/moderation.py

- Current behavior: send a warning about the second post, delete the third and subsequent postings
- Proposed behavior: delete the second and subsequent postings
"public" discussion: https://discord.com/channels/238956364729155585/892125731600101406/1256106776986652693
contributor discussion: https://discord.com/channels/238956364729155585/1040360228388098159/1256324629723877487

enhancement: Delete all multiposts (rather than just after the third posting)

---

cogs/moderation.py

Current behavior: deletes duplicate posts up to 120 seconds after the original post
Proposed behavior: 600 seconds
also:
- deletes some unused methods & variables that should have been removed in #295 
- uses `bisect` instead of linear search (more prevalent optimization since we will be storing 5x as much content)
relevant discussion: https://discord.com/channels/238956364729155585/892125731600101406/1260518966519136267

enhancement: Extend multipost detection to 10 minutes

---

cogs/alerts.py
cogs/dictionary.py
cogs/staffapps_backend.py
message_formatting/embeds.py
util/limiter.py

Implements #301
Currently, we only alert on initial messages but do not consider when keywords are edited in after-the-fact.
This PR adds functionality to keep track of every alert we send. When a message is edited, we scan it for keywords and compare those keywords to the keywords in the alerts we have already sent. If there are new keywords present, which haven't been alerted on yet, we will send a new alert.
We only keep track of alerts for 6 hours, since it is impractical to store this data indefinitely and nearly 100% of message edits take place within the first few minutes anyway. This does mean that a user may be alerted more than once about a message with the same keywords if it is edited after 6 hours, although this will be exceedingly rare.
Demo: …

enhancement: Alert on message edits, too
